apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: przacr.azurecr.io/prz-child
  newName: przacr.azurecr.io/prz-child
  newTag: 1e51f8b5
- name: przacr.azurecr.io/prz-mother
  newName: przacr.azurecr.io/prz-mother
  newTag: 1e51f8b5
resources:
- ../../base
