apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: przacr.azurecr.io/prz-child
  newName: przacr.azurecr.io/prz-child
  newTag: bf8b2e72
- name: przacr.azurecr.io/prz-mother
  newName: przacr.azurecr.io/prz-mother
  newTag: bf8b2e72
resources:
- ../../base
