name: Terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Co wykonać?'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy

permissions:
  contents: read

env:
  ARM_CLIENT_ID:       ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET:   ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_TENANT_ID:       ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  TF_VAR_github_pat:   ${{ secrets.GH_PAT }}

jobs:
  terraform:
    name: Terraform ${{ github.event.inputs.action }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6.0.2

      - name: Azure Login
        uses: azure/login@v3.0.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Utwórz backend storage (idempotentny)
        run: |
          az group create \
            --name PRZ-tfstate \
            --location polandcentral \
            --output none

          az storage account create \
            --name przterraformstate \
            --resource-group PRZ-tfstate \
            --location polandcentral \
            --sku Standard_LRS \
            --allow-blob-public-access false \
            --output none

          az storage container create \
            --name tfstate \
            --account-name przterraformstate \
            --auth-mode login \
            --output none

          echo "Backend storage gotowy"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "~1.7"

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        working-directory: terraform
        run: terraform apply -auto-approve tfplan

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        working-directory: terraform
        run: terraform destroy -auto-approve

      - name: Pobierz kubeconfig AKS
        if: github.event.inputs.action == 'apply'
        run: |
          az aks get-credentials \
            --resource-group PRZ \
            --name PRZAKSCluster \
            --overwrite-existing \
            --only-show-errors

      # ── APLIKUJ ARGOCD APPLICATION PO APPLY ─────────────────────────────────
      - name: Zaaplikuj ArgoCD Application
        if: github.event.inputs.action == 'apply'
        run: kubectl apply -f argocd/application.yaml
